/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
/* tslint:disable */
export var styles = ['main[_ngcontent-%COMP%] {\r\n  padding: 1em;\r\n  font-family: Arial, Helvetica, sans-serif;\r\n  text-align: center;\r\n  margin-top: 50px;\r\n  display: block;\r\n}\r\nh1[_ngcontent-%COMP%] {\r\n    font-weight: bold\r\n}'];
//# sourceMappingURL=app.component.css.shim.js.map