/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../../app/components/protocols/protocols.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
var renderType_ProtocolsComponent_Host:import0.RenderComponentType = (null as any);
class _View_ProtocolsComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ProtocolsComponent_0_4:import3.ProtocolsComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ProtocolsComponent_Host0,renderType_ProtocolsComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('hpt-protocols',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ProtocolsComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ProtocolsComponent_0_4 = new import3.ProtocolsComponent();
    this._appEl_0.initComponent(this._ProtocolsComponent_0_4,[],compView_0);
    compView_0.create(this._ProtocolsComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ProtocolsComponent) && (0 === requestNodeIndex))) { return this._ProtocolsComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ProtocolsComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ProtocolsComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ProtocolsComponent_Host === (null as any))) { (renderType_ProtocolsComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_ProtocolsComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ProtocolsComponentNgFactory:import9.ComponentFactory<import3.ProtocolsComponent> = new import9.ComponentFactory<import3.ProtocolsComponent>('hpt-protocols',viewFactory_ProtocolsComponent_Host0,import3.ProtocolsComponent);
const styles_ProtocolsComponent:any[] = [];
var renderType_ProtocolsComponent:import0.RenderComponentType = (null as any);
class _View_ProtocolsComponent0 extends import1.AppView<import3.ProtocolsComponent> {
  _el_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ProtocolsComponent0,renderType_ProtocolsComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.init([],[this._el_0],[],[]);
    return (null as any);
  }
}
export function viewFactory_ProtocolsComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ProtocolsComponent> {
  if ((renderType_ProtocolsComponent === (null as any))) { (renderType_ProtocolsComponent = viewUtils.createRenderComponentType('c:/Users/sshrestha/Source/Repos/Hamilton Plate Tracker Spa/src/app/components/protocols/protocols.component.ts class ProtocolsComponent - inline template',0,import8.ViewEncapsulation.None,styles_ProtocolsComponent,{})); }
  return new _View_ProtocolsComponent0(viewUtils,parentInjector,declarationEl);
}